### ISSUE TITLE
Lack of support for email forwarders

### ISSUE THREAD

**Issue by ad-m** [kuzmiigo/python-directadmin#1]
Hello,

As in title. There is no support for email forwarders. There is a example implementation:
https://github.com/arian/DirectAdminApi/blob/master/Source/DA/Forwarders.php#L49

Greetings,

**Comment by kuzmiigo** [comment]
Hi,

I guess, you have opened this issue by mistake. As the repo description says:

> Python implementation of Directadmin's Web API. UNOFFICIAL personal repo, see homepage for official SVN repo. http://code.google.com/p/python-directadmin/

This is an old personal repo I haven't touched in 5 years, so I'm going to close the issue.

Thanks.
